// aws-exports.js
// This file is generated by the Cloud team after setting up AWS services.
// Do NOT commit real values to git — use environment variables in CI/CD.
// The Cloud team provides this file after completing the Amplify setup.

const awsConfig = {
  // Cognito — user authentication
  // Cloud team: create a Cognito User Pool and fill these in
  Auth: {
    Cognito: {
      userPoolId:       'REPLACE_WITH_USER_POOL_ID',       // e.g. af-south-1_xxxxxxxxx
      userPoolClientId: 'REPLACE_WITH_USER_POOL_CLIENT_ID', // e.g. 1234567890abcdefghijklmno
      loginWith: {
        email: true,
      },
    }
  },

  // S3 — document storage for invoice uploads
  // Cloud team: create an S3 bucket with Amplify access and fill these in
  Storage: {
    S3: {
      bucket: 'REPLACE_WITH_S3_BUCKET_NAME',
      region: 'af-south-1',
    }
  },

  // API — points to the TradeCore backend on ECS
  // Cloud team: replace with the ALB DNS name after ECS deployment
  API: {
    REST: {
      TradeCoreAPI: {
        endpoint: 'REPLACE_WITH_ALB_URL', // e.g. https://api.tradecore.yourdomain.com
        region:   'af-south-1',
      }
    }
  }
};

export default awsConfig;
